project_name: gobypass403
builds:
  - id: gobypass403
    main: ./cmd/gobypass403/
    binary: bin/gobypass403
    goos:
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1