builds:
  - id: gobypass403
    main: ./cmd/gobypass403
    binary: gobypass403
    goos: [windows]
    goarch: [amd64]
    env: [CGO_ENABLED=1]
    ldflags:
      - -X github.com/slicingmelon/gobypass403/core/cli.GOBYPASS403_VERSION={{.Version}} -s -w

before:
  hooks:
    - go mod tidy

# this is fine
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  draft: true
  prerelease: auto
  disable: false