project_name: go-bypass-403
builds:
  - id: go-bypass-403
    main: ./cmd/go-bypass-403/main.go
    binary: bin/gobypass403
    goos:
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0