project_name: go-bypass-403
builds:
  - id: go-bypass-403
    main: ./cmd/go-bypass-403/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archive:
  format: zip
release:
  github:
    owner: username
    name: repo