# .github/workflows/release.yml
name: Build GoBypass403

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

jobs:
  build-linux-macos:
    name: Build for Linux & macOS
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.6

      - name: Install build deps
        run: sudo apt-get update && sudo apt-get install -y gcc-multilib

      - name: Build
        env:
          CGO_ENABLED: 1
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p bin
          go build -v -o bin/gobypass403-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/go-bypass-403

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: gobypass403-${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin/

  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.6

      - name: Build
        env:
          CGO_ENABLED: 1
        run: |
          mkdir bin
          go build -v -o bin/gobypass403-windows-amd64.exe ./cmd/go-bypass-403

      - name: Upload Windows Binary
        uses: actions/upload-artifact@v4
        with:
          name: gobypass403-windows-amd64
          path: bin/
